### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by dajare** [gvtulder/edward-whymper_scrambles-amongst-the-alps-in-the-years-1860-69#1]
- [x] **Cover** : `cover.jpg` is 1.2Mb, but at [compressjpeg.com](https://compressjpeg.com/) (handy tool!), it takes it down to 487Kb without any visual compromise. (You may well know other such.) Please compress and replace.
- [x] **typography** : `se typogrify .` makes changes in three files; as far as I can see, these should all be accepted, but do check the `diff` before commiting!.
- [x] **modernize spelling/dashes** : `se modernize-spelling` makes a number of changes; it looks like NOT all should be accepted (e.g. "Depot" in French in chapter-9; "Guide-book" should, I think, be retained as it is part of a book title in the endnotes.) Re-run, check, commit.
- [x] **Semantics** : `se semanticate` makes changes, NOT all of which should be accpeted. MANY (32×) are treating the `i` in `appendix-i`’s ID as if it is a Roman numeral, these can be reverted in a single regex pass; it also wants to next `Jos. Mar.` as two `abbr`s, but this looks correct to me as it stands; also `St.` in `chapter-8/line-40` should NOT get abbr tags (in ALT text). But the rest look like they should be accepted (again, check diff!).
- [x] **clean** : `se clean` wants to make changes to `local.css` : please re-run `clean` and check its work; it might be that it should be ignored, but it's not clear to me what some of your rules are intended to do. (My results might come from se v.2.7.1 which I'm still running; could affect other notes below.)
- [x] **diacritics** : `se find-mismatched-diacritics` finds 24 cases. Most of these look explicable from French v. English language contexts, but not all. Please re-run and check output.
- [x] **build-images** : for some reason `se build-images` makes a change to `cover.source.tif`, and since this is a binary file, I don't know what change it's making; please re-run `build-images` and check.
- [ ] **Editorial** : 
    - [x] d5a54f6 : this commit does not look "Editorial" to me; mostly it integrates spans and italics, none of which (so far as I can see) are "blocklevel", even though the "Block-level italics" rules have been added in this commit to `local.css` (also not "Editorial" = ED). So this commit should be re-named in a `git rebase`. (IF "rebase" is new to you—which I doubt!—there are lots guides you can find, or instructions in the SE group I can point you to.)
    - [x] d470c80 : again, italics for French strings, not ED -> rebase to rename.
    - f958a6a : `down hill` -> `downhill` : I would have left as `down hill` (there are *many* examples in the corpus), but I don't think this commit is worth dropping. I noted it here just for the record.
    - [x] 687bee0 : Not an ED commit, so needs to be renamed.
    - [x] f3827a3 : slightly problematic, as this commit does two things: adds `cite` tags (not ED); removes trailing periods (this *is* ED). So this commit should be split into two and the commits appropriately labelled.
    - [ ] 1ca38b2 : This is a titlecasing commit; I'm a bit conflicted here, as there are a number of other ED commits that change case, but changing titlecase in the Step-by-step guide is bundled with `typogrify` changes, and is *not* ED. I'm inclined to suggest it should be NON-ED, but will check on Google Groups for further input.
    - [x] 326803a : it seems adding ALT text is *not* ED, since it is not altering any book content (there are no commits in the SE corpus adding ALT text that are editorial, [none I could find](https://github.com/search?q=owner%3Astandardebooks+alt+text&type=commits) anyway!
    - [x] 9d5baf8 ... 9b3047a :  adding/removing language semantics is not ED; one (or two?) of these also alter spelling or add punctuation, which (as I understand it) *is* ED. Please review this whole set [listed out below][^list1]
    - [x] c55ab13 : `en fête` was fine in ital+semantics (MW lists it as "[French phrase](https://www.merriam-webster.com/dictionary/en%20fete)"; contrast, e.g., its entry for "[père](https://www.merriam-webster.com/dictionary/pere)")
    - [x] 2bfd053 : adding ital+semantics (to `Hyperion`) not ED
    - [x] e344eb0 ... ee8db8c : Another set of italics removals that look non-ED; please see [second list below][^list2] 
    - [x] 20b2a47 8d4ba4f 074e0b8 dc6661f 6ebe836 79e9c7e eead830 : more italics-removal commits, non-ED 
- [ ] **Emphasis** : `<em>esprit de corps</em>` and `<em>per guide</em>` do not look like emphasis to me; there might be some others, too, but these at least look like they should simply be normal text. There are 421 cases of `em` tags, and it would be good just to run your eye over them to be sure. (The few unsemanticated `i` tags look fine.)
- [ ] **local.css** : I freely admit that my CSS skills are not up to a proper review of `local.css`. I have dutifully gone through its 623 lines, though, 
```
#note-53 tr:first-child th,
#note-53 tr:first-child td{
	padding-top: 0.5em;
}

#note-53 tr:last-child th,
#note-53 tr:last-child td{
	padding-bottom: 0.5em;
}
```
might be collapsed (`padding: 0.5em 0;`), I'm not confident in setting the L/R value. But this will need Alex (or other more knowledgeable editor) for proper review.
- **Other fixes:**
    - [x] `appendix-c`/line 119 : the `span` tags here should be `i`; same change for illustration-135 in the LOI.
    - [x] chapter-15/line 69 : `<time date="1864">1864</time>` -> `datetime="`
    - [x] **build --check-only** : complains about endnotes.xthml line 358, `<td scope="col"/>`, but I don't know what might be the problem here, if in fact there is one.

---

This is a really very complex production, and much moreso than any I've done in my 36 to date! So my review should be taken with a grain of salt, and I will flag this up also in the Google Groups thread when I post notice of the review. There is a huge amount of work here which I must imagine was something of a labour of love.

---

[^list1]: 
(First list) These contiguous commits are (all? mostly) not ED:
* 9d5baf8: 2024-09-23 00:05 | [Editorial] Add italics/language: montagnes. [Gijs van Tulder]
* 789a882: 2024-09-23 00:05 | [Editorial] Add italics/language: têtes arrondies. [Gijs van Tulder]
* 9b37832: 2024-09-23 00:05 | [Editorial] Add italics/language: ajusteurs. [Gijs van Tulder]
* 9e1ff78: 2024-09-23 00:05 | [Editorial] Add language/italics: perforatrices. [Gijs van Tulder]
* 1886c45: 2024-09-23 00:05 | [Editorial] Italics/language: compresseur à pompe/choc. [Gijs van Tulder]
* 81fc2c6: 2024-09-23 00:05 | [Editorial] Remove language/italics: air. [Gijs van Tulder]
* 3caaf1f: 2024-09-23 00:05 | [Editorial] Remove language/italics: la Serra -> “la Serra”. [Gijs van Tulder]
* 965ff2d: 2024-09-23 00:05 | [Editorial] Spelling, language/italics: salle à manger. [Gijs van Tulder]
* f7f40cd: 2024-09-23 00:05 | [Editorial] Remove italics: capped. [Gijs van Tulder]
* 50dfd72: 2024-09-23 00:05 | [Editorial] Remove italics/language: habitués. [Gijs van Tulder]
* 3bcdabb: 2024-09-23 00:05 | [Editorial] Spelling/language: clientèle -> clientele. [Gijs van Tulder]
* 52d3dc5: 2024-09-23 00:05 | [Editorial] Remove italics/language: bureau. [Gijs van Tulder]
* 79ce447: 2024-09-23 00:05 | [Editorial] Italics to quotes: veined structure. [Gijs van Tulder]
* 59341a6: 2024-09-23 00:05 | [Editorial] Remove italics/language: Monsieur, Messieurs. [Gijs van Tulder]
* 8fd23df: 2024-09-23 00:05 | [Editorial] Remove italics/language: schrund, bergschrund. [Gijs van Tulder]
* 73e1c09: 2024-09-23 00:05 | [Editorial] Remove italics/language: cirque. [Gijs van Tulder]
* 992ef5e: 2024-09-23 00:05 | [Editorial] Remove italics/language: cabaret. [Gijs van Tulder]
* 0a3a580: 2024-09-23 00:05 | [Editorial] Remove italics/language: en masse. [Gijs van Tulder]
* 4ca79cc: 2024-09-23 00:05 | [Editorial] Add italics/language: courant ascendant. [Gijs van Tulder]
* ecd5702: 2024-09-23 00:05 | [Editorial] Remove italics/language: carte blanche. [Gijs van Tulder]
* 2609b6b: 2024-09-23 00:05 | [Editorial] Remove italics/language: col. [Gijs van Tulder]
* 75dceb3: 2024-09-23 00:05 | [Editorial] Add italics/language: Diable. [Gijs van Tulder]
* 1ec5ca9: 2024-09-23 00:05 | [Editorial] Remove language/italics: éclat. [Gijs van Tulder]
* 92591de: 2024-09-23 00:05 | [Editorial] Add language/italics: cheminée. [Gijs van Tulder]
* 5cb2c26: 2024-09-23 00:05 | [Editorial] Remove language/italics: cordon. [Gijs van Tulder]
* 95d897c: 2024-09-23 00:05 | [Editorial] Add language/italics: affût. [Gijs van Tulder]
* 9b3047a: 2024-09-23 00:05 | [Editorial] Remove language/italics: café noir. [Gijs van Tulder]

[^list2]: 
(Second list) Not ED commits (I removed 8a342ea which included spelling change) - please review:
* e344eb0: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: cabane. [Gijs van Tulder]
* d4ecfd5: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: dicta. [Gijs van Tulder]
* 4a14a64: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: vice versa. [Gijs van Tulder]
* f2d6abd: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: the moraine. [Gijs van Tulder]
* ff920da: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: stumps. [Gijs van Tulder]
* 4298dd9: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: sounds. [Gijs van Tulder]
* 06ea87c: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: planed by a plane. [Gijs van Tulder]
* b1e832c: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: rotundity. [Gijs van Tulder]
* bea3b1c: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: windward. [Gijs van Tulder]
* e4e5298: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: table d'hôte. [Gijs van Tulder]
* 7ce7dbe: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: sou. [Gijs van Tulder]
* df46b16: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: rognon. [Gijs van Tulder]
* 047e7f4: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: physique. [Gijs van Tulder]
* a94ec0a: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: modus operandi. [Gijs van Tulder]
* 6f234b1: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: massif. [Gijs van Tulder]
* a55a024: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: genus. [Gijs van Tulder]
* 6146b5c: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: père, fils. [Gijs van Tulder]
* 78f6cea: 2024-09-23 Mon 00:05 | [Editorial] Remove language: esprit de corps. [Gijs van Tulder]
* ee8db8c: 2024-09-23 Mon 00:05 | [Editorial] Remove italics: en route. [Gijs van Tulder]

**Comment by dajare** [comment]
@gvtulder - Just wondering how things are progressing? Hope all's well at your end! D.

**Comment by gvtulder** [comment]
Hi @dajare. Thanks for the review. A bit later than I originally planned (apologies for the delay -- I was quite busy with work) I've addressed most of your comments.

Some remarks below, with a few open questions marked with a checkbox.

As I wrote before, there are some issues in version 2.7.1 of the tools (most importantly in `se clean`) that are fixed in the development version on GitHub. For that reason, it might be useful to wait for the release of 2.7.2 before finalizing this.

You'll have noticed that I am not in a hurry, but I look forward to your response when you have time to look at this!

------

- [ ] **typogrify**:
  All false positives, I think, with a question mark for the ditto marks.

  * `src/epub/content.opf`:
    All changes add en-dashes in the number ranges in the title.
    * Adding an [en-dash in the URL](https://github.com/gvtulder/edward-whymper_scrambles-amongst-the-alps-in-the-years-1860-69/blob/5fd2b914df9c0278b9642798e9579f1c23afd033/src/epub/content.opf#L4): I assume this needs to stay a normal hyphen.
    * The [alternate titles](https://github.com/gvtulder/edward-whymper_scrambles-amongst-the-alps-in-the-years-1860-69/blob/5fd2b914df9c0278b9642798e9579f1c23afd033/src/epub/content.opf#L31-L38): the main title has the en-dash, but I added a versions with a standard hyphen in the list of alternate titles.
  * `src/epub/text/colophon.xhtml`:
    Adding an em-dash to the URL.
  * [ ] `src/epub/text/appendix-d.xhtml`:
    In the table, I used a [series of non-breaking spaces](https://github.com/gvtulder/edward-whymper_scrambles-amongst-the-alps-in-the-years-1860-69/blob/5fd2b914df9c0278b9642798e9579f1c23afd033/src/epub/text/appendix-d.xhtml#L161) to position the ditto marks. se typogrify wants to collapse these to a single space. SEMoS 8.7.1 asks that "Sentences are single-spaced", but is this really a sentence?
    I could probably place them apart with CSS, if necessary, but keeping the spaces is much more straightforward.
  * `src/epub/text/endnotes.xhtml`:
    Similar: removing spaces separating ditto marks.

- **modernize-spelling**:
  All false positives, I would say. It wants to:
  * Change Sion to Zion: it's a French place name.
  * Remove the accent from débris in a French sentence.
  * Remove the hyphen from To-night in a poem.
  * Remove the accent from Dêpot de la Guerre, but it's a French name.
  * Remove the hyphen from Snow-Bound: the title of a poem.
  * Adding an accented è in pere: this is part of the patois sentences, where everything is written without accents.
  * Remove the hyphen from Guide-Book: it's part of the title of a book.
  * Change "se distingue" to "se distingué" in a French sentence: the book writes it without the accent, which is the correct spelling.

- **semanticate**:
  All false positives.
  * The appendix-i.xhtml Roman numeral problem is fixed in the development release of the tools.
  * It wants to make "Col." an abbr name-title, but this refers to the French word for a mountain pass. (Capitalized because it's part of the place name.)
  * It adds an abbr tag to "St." inside the alt text of an image.
  * It sees a Roman numeral in the Swedish title "En Sommer i Copenhagen".
  * It adds an extra abbr inside `<abbr>Jos. <abbr>Mar.</abbr></abbr>`.

- **clean**:
  All false positives. The development version from GitHub does not make any changes, the latest released version breaks the CSS.

- **find-mismatched-diacritics**:
  I checked them again, and they all look correct.

  There is a bunch of French/English mismatches, and the patois adds a few exceptions as well (e.g., père/pere, because the patois is mostly written without accents).

- **build-images**:
  Should be fixed now. For some reason I was running a different pillow version (10.4.0 instead of 10.3.0), which made slightly different changes to the metadata of cover.source.tif.


- **Emphasis**:
  * General sidenote first: I must admit that I find these things a bit tricky, because in some cases I have the impression that the combination of foreign language plus italics might have been intentional. The phrase "salle à manger", for example, appears in the dictionary, so I have removed the italics, but it's not just a neutral word: the author could have written "dining room" instead, but intentionally chose to use the (italicized) French word. Is it reasonable to completely de-emphasize that? Similar for a sentence like

    > Biener, made secure, cried, “Come on, sir,” and *Monsieur* endeavoured.

    I have removed the italics, but the choice for a French word does seem quite intentional. It's difficult to judge.

  * "esprit de corps": emphasis removed.
  * "per guide" (note 337, page 351 of the book): I have kept the emphasis for now. In the main text, the author discusses the economics of the "perennial flow of francs" brought in by tourists. In this context, I suspect that a note that says the price for an ascent "is now placed at £4 *per guide*" could very well use italics to emphasize the author's surprise. (Unless you think that "per guide" is French, but even then the emphasis does not seem out of place.)
  * I looked again at the other `<em>` tags. They are all italicized in the book, and are not French words, so I think these are all genuine instances with emphasis. (The author does seem quite fond of his italics, that's true.)
  * [ ] One exception perhaps: the initial sentences at the [end of Appendix G](https://github.com/gvtulder/edward-whymper_scrambles-amongst-the-alps-in-the-years-1860-69/blob/02d75258adb2eddc7e2db7f0b0f61e8db1372b0e/src/epub/text/appendix-g.xhtml#L26-L47). These sentences are printed in italics, but you could argue that this is formatting instead of true emphasis. Would a `<i>` be more appropriate?

- **build --check-only**:
  * Fixed the complaint about `endnotes.xhtml`: in `<td scope="col"/>`, I think epubcheck doesn't like the scope on an empty element. I've removed the scope and now it works.
  * There is still an epubcheck complaint about the CSS. `figure:not(:has(figure))` looks correct to me, it works and passes the W3C CSS validator, but it seems that epubcheck doesn't correctly parse the :has and :not pseudo-classes.

- **`local.css`**:
  Maybe I misunderstand your suggestion, but I don't think these two rules can be merged: the first is for first-child, the second for last-child.

- **Non-editorial italics/language commits**:
  I've gone through the Editorial commits and removed the `[Editorial]` from commits that only change italics/language tasks, as indicated in your two lists.

- [ ] **Possibly editorial**:
  You wrote (link to the old commit):
  > 1ca38b2 : This is a titlecasing commit; I'm a bit conflicted here, as there are a number of other ED commits that change case, but changing titlecase in the Step-by-step guide is bundled with typogrify changes, and is not ED. I'm inclined to suggest it should be NON-ED, but will check on Google Groups for further input.

  I've removed the Editorial flag, but let me know if it should be changed back.

**Comment by dajare** [comment]
@gvtulder - Thanks, Gijs! Hopefully I'll get time over the weekend to work through this.

**Comment by dajare** [comment]
@gvtulder Apologies for the delay, Gijs; it has been very busy here! I hope to finish this today, or possibly tomorrow. Thanks for your patience!

**Comment by dajare** [comment]
Okay - well done on responding to all of those matters, and for the further refinement of the project. We've come to the limits of my capacity to have input on this, so time to hand over to Alex. Further updates on [Google Groups](https://groups.google.com/g/standardebooks/c/ZeL1AvgGKqM), then.

**Comment by gvtulder** [comment]
@dajare Thanks!

**Comment by dajare** [comment]
@gvtulder - It's great to see this finally published! Thanks for your patience and perseverance. It really is an impressive accomplishment. :tada:
